// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserId) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId       uint64                 `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductQuantity uint64                 `protobuf:"varint,4,opt,name=product_quantity,json=productQuantity,proto3" json:"product_quantity,omitempty"`
	PricePerUnit    uint64                 `protobuf:"varint,5,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Product) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Product) GetProductQuantity() uint64 {
	if x != nil {
		return x.ProductQuantity
	}
	return 0
}

func (x *Product) GetPricePerUnit() uint64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ProductId) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductsInBasket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsInBasket) Reset() {
	*x = ProductsInBasket{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsInBasket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsInBasket) ProtoMessage() {}

func (x *ProductsInBasket) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsInBasket.ProtoReflect.Descriptor instead.
func (*ProductsInBasket) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ProductsInBasket) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type WalletMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletMessage) Reset() {
	*x = WalletMessage{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletMessage) ProtoMessage() {}

func (x *WalletMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletMessage.ProtoReflect.Descriptor instead.
func (*WalletMessage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *WalletMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletMessage) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"!\n" +
	"\x06UserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xa2\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x04R\tproductId\x12)\n" +
	"\x10product_quantity\x18\x04 \x01(\x04R\x0fproductQuantity\x12$\n" +
	"\x0eprice_per_unit\x18\x05 \x01(\x04R\fpricePerUnit\"*\n" +
	"\tProductId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"=\n" +
	"\x10ProductsInBasket\x12)\n" +
	"\bproducts\x18\x01 \x03(\v2\r.user.ProductR\bproducts\"K\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\rWalletMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount2\xbe\x03\n" +
	"\vUserService\x125\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\f.user.UserId\"\x00\x124\n" +
	"\n" +
	"DeleteUser\x12\f.user.UserId\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\vToUpBalance\x12\x13.user.WalletMessage\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\rToDownBalance\x12\x13.user.WalletMessage\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\x15GetProductsFromBasket\x12\f.user.UserId\x1a\x16.user.ProductsInBasket\"\x00\x12=\n" +
	"\x12AddProductToBasket\x12\r.user.Product\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x17DeleteProductFromBasket\x12\x0f.user.ProductId\x1a\x16.google.protobuf.Empty\"\x00B\x15Z\x13user_service/api/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*UserId)(nil),            // 0: user.UserId
	(*Product)(nil),           // 1: user.Product
	(*ProductId)(nil),         // 2: user.ProductId
	(*ProductsInBasket)(nil),  // 3: user.ProductsInBasket
	(*CreateUserRequest)(nil), // 4: user.CreateUserRequest
	(*WalletMessage)(nil),     // 5: user.WalletMessage
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	1, // 0: user.ProductsInBasket.products:type_name -> user.Product
	4, // 1: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	0, // 2: user.UserService.DeleteUser:input_type -> user.UserId
	5, // 3: user.UserService.ToUpBalance:input_type -> user.WalletMessage
	5, // 4: user.UserService.ToDownBalance:input_type -> user.WalletMessage
	0, // 5: user.UserService.GetProductsFromBasket:input_type -> user.UserId
	1, // 6: user.UserService.AddProductToBasket:input_type -> user.Product
	2, // 7: user.UserService.DeleteProductFromBasket:input_type -> user.ProductId
	0, // 8: user.UserService.CreateUser:output_type -> user.UserId
	6, // 9: user.UserService.DeleteUser:output_type -> google.protobuf.Empty
	6, // 10: user.UserService.ToUpBalance:output_type -> google.protobuf.Empty
	6, // 11: user.UserService.ToDownBalance:output_type -> google.protobuf.Empty
	3, // 12: user.UserService.GetProductsFromBasket:output_type -> user.ProductsInBasket
	6, // 13: user.UserService.AddProductToBasket:output_type -> google.protobuf.Empty
	6, // 14: user.UserService.DeleteProductFromBasket:output_type -> google.protobuf.Empty
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
